---
# Create by App::VTide::Command::Init Sun Aug 11 20:04:50 2019 VERSION 0.1.10
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    eg:
      - some-file.eg
name: apt-perl
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2: []

  3: []

  4: []

